name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        uses: ./.github/actions/tests

  standards:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run code standards
        uses: ./.github/actions/standards
